### PR TITLE
added may 12 livecoding.tv

### PR DESCRIPTION
**Pull request by kindohm**
This stream has no embed code, unfortunately, but the permalinks are there. 

I also have a number of other historic streams to add, if that's useful.

### CODE REVIEW

**Comment by yaxu** [comment]
Hey Mike, I think it'd be good to just include streams that can be embedded on the site. Could you maybe upload the video to archive.org, if you're happy with it being creative commons?

**Comment by yaxu** [comment]
Just had a look at livecoding.tv terms. They are (predictably) pretty shitty, but are at least nonexclusive..

**Comment by yaxu** [comment]
Just grabbed the video, any objections to me testing out an upload to archive.org?

**Comment by kindohm** [comment]
@yaxu sure, give it a try. how did you grab the video? It appears that I've neglected to use a "record" feature of the broadcasting software, which should allow me to record streams to disk for upload somewhere else later. If I continue to stream on livecoding.tv I'll definitely take advantage of that.

**Comment by yaxu** [comment]
With mplayer -dumpstream rtmp://usmedia4.livecoding.tv:1935/vod/kindohm-1431486013.flv?t=9D3E221B00C24E6EB0CBE143BAB1D777

Actually it's still running

**Comment by yaxu** [comment]
OK trying an upload now.. I think in general it'd be good to have streams embedded in the site when they're live, then archived, but lets try to put this one up to test.

**Comment by kindohm** [comment]
ok got it. that makes sense. digressing here, but I don't know if I'll use livecoding.tv any more unless their site matures more. twitch.tv and Google hangouts have much better options for embedding and exporting. Of course I could try and roll my own stream but I don't really have the appetite for that :neutral_face:

**Comment by yaxu** [comment]
Yep there's an icecast server running on eulerroom.com but I don't know if it's easily possible to screencast to that from windows

**Comment by kindohm** [comment]
If the spirit of euler room is to list and archive its own screencasts then
we can ignore this pull request

**Comment by yaxu** [comment]
I'm not sure what the spirit of eulerroom is yet, but it's probably better to use external streaming/archiving services.. Icecast is good but won't scale to many users on my server, and likewise archiving it on there isn't going to work. Lets try a few different things. I think including the live event as well as the archive would be good in general though.

**Comment by yaxu** [comment]
What do you think about this?
https://archive.org/details/eulerroom2

**Pull request closed without merging**
