### PR TITLE
display local time

### PR DESCRIPTION
**Pull request by kindohm**
Times now display in user's local time. Using [moment.js](http://momentjs.com/) to make dates easy, rather than hand-rolling custom js. 

Moment.js used to have support for showing the local time zone name, but that feature has been deprecated because the information available from browsers is not reliable.

### CODE REVIEW

**Comment by yaxu** [comment]
Thanks for the PR! A huge improvement.. It would be good if we could specify the local tz I think, so we can show both local times. I guess we can use moment.js for that?

**Comment by kindohm** [comment]
If the author specifies the time zone, then that should work. moment.js does have a great plugin for tz-specific features: [http://momentjs.com/timezone](http://momentjs.com/timezone). It just can't detect the user's local time zone through the browser. I'll run with this and see what I can get to work.

**Comment by kindohm** [comment]
ok this is working with the following constraints:
1. author specifies date and time in the event's time zone
2. author specifies the event's time zone
3. post can display the event's date and time in both the event's time (with timezone label) and user's local time (with no timezone label).

I guess the biggest question is what to actually display. It might get crowded trying to display the event time in both the event's timezone and also the user's local time zone.

**Comment by kindohm** [comment]
There more I look at this the more I think it's a bad idea to automatically determine how to display the event's date/time for the local user. When you start including daylight savings time and problematic date issues, we can't make assumptions about UTC offsets and simple math to determine a new display value. 

If we really want to display the event in the user's time zone, then we should require the user to specify their time zone (maybe set a cookie to remember, etc).

Perhaps we should just keep this simple avoid displaying the user's local time at all. Maybe just display the event's time zone time and maybe the UTC time also. thoughts?

**Comment by kindohm** [comment]
figured it out a clean way to do it with pure moment usage and no silly math. separate PR coming sometime soon...

**Pull request merged**
